name: Publish

on:
    push:
        tags:
            - '*'

permissions:
    contents: write
    id-token: write

jobs:
    publish-jsr:
        name: Publish to JSR
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v1
            - run: deno publish
